# Generated by Django 3.2.7 on 2021-10-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rate',
            new_name='avg_rate',
        ),
    ]
