# Generated by Django 3.2.7 on 2021-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211023_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='design_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='usability_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
