# Generated by Django 3.2.7 on 2021-10-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211023_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content_rate',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability_rate',
        ),
    ]
